/** Declaration file generated by dts-gen */

export = mongoose_bcrypt;

declare function mongoose_bcrypt(schema: any, options?: any): any;

declare namespace mongoose_bcrypt {
	const prototype: {
	};

	function verifyPasswordSync(password: string): boolean;

}

